type = "about"
title = "About"

[profile]
research_interests = [
  "Computer Vision",
  "Active Learning",
  "Representation Learning",
  "information Retrieval"
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "About"

[[sections]]
id = "timeline"
type = "timeline"
source = "timeline.toml"
title = "Journey"
