[[entries]]
period = "2025"
content = "I moved to Heidelberg, Germany"

[[entries]]
period = "2024–2025"
content = "In the spring of 2024, I moved to Geneva, Switzerland as a full time ML Engineer for WIPO, United Nations"

[[entries]]
period = "2021–2023"
content = "I decided to make a transition from Finance to Computer Science, completed CS courses, master thesis experiments, and my first ML engineer internship in Zurich"

[[entries]]
period = "2018–2020"
content = "I moved to St.Gallen, Switzerland, which is the place I have stayed the most time other than my hometown. Enjoyed courses at HSG and explored Europe"

[[entries]]
period = "2013–2018"
content = "I completed my bachelor's degree in Economics at Yuanpei College, Peking University and spent one year as main contributor to two research reports at Tsinghua University, focusing on industry research in insurtech & fintech"
